### ISSUE TITLE
[Request] Update the dependencies

### ISSUE THREAD

**Issue by s0h3ck** [securisec/glorifiedgrep#3]
Could you please update the dependencies and add a new version in the PyPI to avoid the `error: Failed buiding wheel for cffi`? I tested with the latest version of cffi, and it works fine. Thanks!

**Comment by securisec** [comment]
I just tested on a linux container, and osx virtualbox and it worked fine with both. I dont think it is a dependency issue with Chepy. Because in the requirements, most of the libraries are not version locked. Build is passing on all three major platforms also. Please make sure to follow the issue template and provide more data on what the error you are getting.

**Comment by securisec** [comment]
Just checked on both osx and used travis to start a fresh build on linux, and it passed both. Cant replicate.

**Comment by s0h3ck** [comment]
To answer your question: I got this bug : https://bitbucket.org/cffi/cffi/issues/403/build-fails-on-38-dev-pyinterpreterstate if I run `pip install glorifiedgrep`.

My workaround is to do a git clone and change the version in the setup.py, but it should be done from PyPI directly.

Do you think you can update the dependency cffi at least to the latest version?

**Comment by securisec** [comment]
I see. It is a python 3.8 issue. I will fix the requirements on the next release and add test cases for python 3.8

**Comment by securisec** [comment]
If possible. `cffi` is a sub requirement for another lib. Most likely one of the crypto libs. If that is the case, have to wait till they update

**Comment by s0h3ck** [comment]
Yes, it is. cffi-1.14.0 and cryptography-2.9 are together. You can update cffi alone. Of course, if you want, it would be better to do a proper update of all dependencies.

**Comment by securisec** [comment]
@s0h3ck I will release the new version in a bit, but both travis and github actions fail with the same cffi issue and i cannot replicate it in my local system. but i did hardcode the requirement for crypto 2.9.
